apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: user-apps
spec:
  acme:
    email: krishanand974@email.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: krishanand974@email.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
