apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orchestrator-role  
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "create", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrator-role-binding
subjects:
- kind: ServiceAccount
  name: orchestrator-sa
  namespace: default  
roleRef:
  kind: ClusterRole
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io